- package.json
- src/mocks/browser.ts
- src/mocks/handlers.ts
- src/mocks/http.ts
- src/services/ApiService.ts
#1 
관련 이슈는 위의 링크를 확인하세요
단, 템플릿이 만들어지기 이전까지만 위와같은 pr을 허용합니당
> msw mocking을 이용한 main page data fetching 구현 - #1

- .github/PULL_REQUEST_TEMPLATE.yml
> PR template 추가 - #19

- src/app/page.tsx
> deploy test: 무중단 배포 되는지 확인 테스트 - #25

- src/app/page.tsx
> deploy test: 무중단 배포 테스트

- ecosystem.config.js
- src/app/page.tsx
> deploy test: pm2 file watch false 변경

- .github/workflows/Deploy.yml
- src/services/apiService.ts
> feat: .env 파일 cicd 파이프라인에서 생성하도록 변경

- .github/workflows/Deploy.yml
> feat: .env.production 생성하도록 수정

- .github/workflows/Deploy.yml
> fix: .env 파일 생성 스크립트 수정

- src/services/apiService.ts
>url을 msw 서버로 해놨던거 백엔드 서버로 변경
>
>
> fix: url을 msw 서버로 해놨던거 백엔드 서버로 변경

- .eslintrc
- next.config.mjs
- package-lock.json
- package.json
- src/app/(post)/posts/[postId]/page.module.scss
- src/app/(post)/posts/[postId]/page.tsx
- src/app/(post)/write/page.tsx
- src/app/page.tsx
- src/components/AddressInput.tsx
- src/components/CategoryList.module.scss
- src/components/CategoryList.tsx
- src/components/Footer.module.scss
- src/components/LiveFriendsList.module.scss
- src/components/LiveFriendsList.tsx
- src/components/Post.module.scss
- src/components/Post.tsx
- src/components/UserIcon.tsx
- src/components/ui/Button.tsx
- src/components/ui/ImageFill.tsx
- src/components/ui/InputBox.tsx
- src/mocks/http.ts
- src/services/apiService.ts
- src/utils/index.ts
#45 
> build시 eslint 에러로 인해 빌드 안되는 문제 수정
>
>
> build시 eslint 에러로 인해 빌드 안되는 문제 수정 - #45

- src/app/(post)/write/page.tsx
> 배포 실패로 인한 다시 PR - #45

- scripts/before-install.sh
> fix: code deploy가 script 실행하기전에 권한을 얻고 삭제하도록 수정

- scripts/before-install.sh
> fix: 배포시에 permission 문제 수정 코드 추가

- scripts/before-install.sh
> fix: 배포 에러 수정

- scripts/before-install.sh
> fix: Permission denied (publickey) 해결

- scripts/after-install.sh
> fix: npm 권한 수정

- scripts/before-install.sh
- src/app/(post)/layout.tsx
- src/app/page.tsx
- src/hooks/useCheckSession.ts
- src/services/apiService.ts
>(auth)와 관련없는 page들이 포함된 layout에 useCheckSession() 커스텀훅으로 로그인 유지 확인
>
>
> [main] session 만료시에 login page로 리다이렉팅 기능 구현 - #59

- src/app/map/page.tsx
> chore: api url 수정-/#12

- next.config.mjs
> https 등록 후 배포url에서 카카오톡 map 작동을 확인한다

- src/services/apiService.ts
> chore: 배포시 kakao Api 안되는 문제 수정 후 확인을 위한 PR

- package-lock.json
- package.json
- src/app/map/page.tsx
- src/app/share/page.module.scss
- src/app/share/page.tsx
- src/components/VoteUrlModal.module.scss
- src/components/VoteUrlModal.tsx
> url 생성하기 버튼 클릭 시 모달창 생성/-#12

- package-lock.json
- src/app/map/page.tsx
- src/app/share/page.tsx
- src/components/VoteUrlModal.tsx
> chore: linting disable

- src/app/store/[storeId]/page.tsx
>  #62 useEffect 의존성 배열 넣지 않은것 수정
>
>
> useEffect 의존성 배열 넣지 않은것 수정 - #62

- src/app/map/page.module.scss
- src/app/map/page.tsx
- src/app/share/page.module.scss
- src/app/share/page.tsx
> feat: 공유맵 마커 출력-#46

- src/app/map/page.module.scss
- src/app/map/page.tsx
- src/app/share/page.module.scss
- src/app/share/page.tsx
- src/app/store/[storeId]/page.tsx
> feat: 공유맵 마커 출력 - #46 

- next.config.mjs
- src/app/live/UserVideoComponent.jsx
- src/app/live/[sessionId]/page.jsx
- src/services/apiService.ts
- test.jsx
> fix: 라이브 스트리밍 참여자가 스트리머의 카메라를 볼 수있도록 수정 - #81

- src/app/live/App.css
- src/app/live/OvVideo.jsx
- src/app/live/UserVideo.css
- src/app/live/UserVideoComponent.jsx
- src/app/live/[sessionId]/page.jsx
- src/app/live/index.css
> [fix] 참여자는 카메라를 보이게 하지 않도록 수정 - #81

- src/app/live/[sessionId]/page.jsx
> [deploy][fix] 참여자가 참여자의 카메라가 아닌 스트리머의 카메라가 보이도록 수정 - #81

- src/app/live/[sessionId]/page.jsx
> [deploy][fix] 참여자의 배열중에 0번째가 스트리머이므로 0번째만 보여지도록 수정 - #81

- src/app/(post)/write/page.tsx
- src/app/map/page.tsx
- src/app/share/page.tsx
> [HOT FIX]: write 리뷰 자동완성 false로  변경

- src/app/share/page.tsx
> #106
unload시 leave session() 호출
내가 나의 subscriber가 되지 않도록 필터링 추가
>
>
> fix: unload시 leave session() 호출 , 내가 나의 subscriber가 되지 않도록 필터링 추가 - #106

- src/app/share/page.tsx
>#106
subscriber변경 시 sendUserData 보내지 않도록 임시 수정
>
>
> chore: subscriber변경 시 sendUserData 보내지 않도록 임시 수정

- src/app/share/page.tsx
> fix: 충돌 방지 롤백

- src/app/share/page.tsx
> fix: publisher음성 제거

- src/app/(post)/write/_component/Spinner.module.scss
- src/app/(post)/write/_component/Spinnner.tsx
- src/app/(post)/write/page.module.scss
- src/app/(post)/write/page.tsx
- src/app/live/_components/LiveHeader.module.scss
- src/components/Footer.module.scss
> #116 
리뷰 자동완성 로딩중에 보여줄 `Spinner` 컴포넌트도 구현완료
>
>
> AI 리뷰 자동완성 기능 구현 완료 - #116

- src/app/share/page.tsx
> [Bug Fix] 투표결과 페이지로 못가던 버그 수정

- .github/workflows/playwright.yml
> [Deploy] playwright 테스트 돌리기전에 local 서버 실행하도록 변경

- src/app/map/page.tsx
- src/app/share/page.module.scss
- src/app/share/page.tsx
- src/components/VoteUrlModal.tsx
> [BUG FIX] build 실패 원인 제거 - #150

- src/components/domain/vote/CandidateStore/CandidateStore.spec.tsx
- src/components/domain/vote/WinnerStoreCard/WinnerStoreCard.stories.tsx
- src/components/ui/UserIcon/UserIcon.tsx
- src/feature/webRTC/services/hooks/useFetchConnectionToken.ts
- src/lib/MapModel.ts
> eslint rule 반영 - #163
